// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK0SzpTBWeQfG0RxMzw2qzCdWXBgilUV4',
    appId: '1:269055085723:web:843a5170eba6faad800a3e',
    messagingSenderId: '269055085723',
    projectId: 'repository-121a3',
    authDomain: 'repository-121a3.firebaseapp.com',
    storageBucket: 'repository-121a3.firebasestorage.app',
    measurementId: 'G-W43KKT694X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBabGcbqh1v3BAaqijdhgzP3rMeNqBpDMU',
    appId: '1:269055085723:android:cc32b388d347fe3d800a3e',
    messagingSenderId: '269055085723',
    projectId: 'repository-121a3',
    storageBucket: 'repository-121a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKYQJ107wK-GZuCFtIf0FbTir0BrBM-_Q',
    appId: '1:269055085723:ios:78ce00c97dc8cccd800a3e',
    messagingSenderId: '269055085723',
    projectId: 'repository-121a3',
    storageBucket: 'repository-121a3.firebasestorage.app',
    iosBundleId: 'com.techtest.repository',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKYQJ107wK-GZuCFtIf0FbTir0BrBM-_Q',
    appId: '1:269055085723:ios:78ce00c97dc8cccd800a3e',
    messagingSenderId: '269055085723',
    projectId: 'repository-121a3',
    storageBucket: 'repository-121a3.firebasestorage.app',
    iosBundleId: 'com.techtest.repository',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK0SzpTBWeQfG0RxMzw2qzCdWXBgilUV4',
    appId: '1:269055085723:web:c705ebd3bb6a5f86800a3e',
    messagingSenderId: '269055085723',
    projectId: 'repository-121a3',
    authDomain: 'repository-121a3.firebaseapp.com',
    storageBucket: 'repository-121a3.firebasestorage.app',
    measurementId: 'G-H0VS1XQB4Z',
  );
}
