source "https://rubygems.org"

gem "fastlane"

# plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
# eval_gemfile(plugins_path) if File.exist?(plugins_path)
gem 'fastlane-plugin-firebase_app_distribution', '0.9.1'
gem 'google-apis-firebaseappdistribution_v1', '0.3.0'
gem 'google-apis-firebaseappdistribution_v1alpha', '0.2.0'
