# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "1800" 
ENV['XCODE_VERSION'] = "14.3.1" 
default_platform(:ios)

platform :ios do
    desc "Import Certificates and Provisioning Profile"
    private_lane :import_certificates_and_provisioning_profile do
        create_keychain(
            name: "ios_app_keychain",
            password: ENV["KEYCHAIN_PASSWORD"],
            timeout: 1800
        )
        import_certificate(
            certificate_path: "ios_distribution.p12",
            certificate_password: ENV["CERT_PASSWORD"],
            keychain_name: "ios_app_keychain",
            keychain_password: ENV["KEYCHAIN_PASSWORD"]
        )

        install_provisioning_profile(path: "adhoc.mobileprovision")
    end

    desc "Archive STG and send to Firebase"
    lane :archive_stg_app_distribution do
        import_certificates_and_provisioning_profile
        build_app(workspace: "Runner.xcworkspace",
            scheme: "Runner",
            configuration: "STG", 
            clean: true,
            export_options: {
                method: "ad-hoc",
                provisioningProfiles: {
                    "com.techtest.repository" => "yumemiprofileAdHoc"
                }
            }
        )

        firebase_app_distribution(
            app: "1:269055085723:ios:78ce00c97dc8cccd800a3e",
            groups: "testers",
            release_notes: "STG環境 テスト配信",
            firebase_cli_path: `which firebase`.strip()
        )
    end
end